### ISSUE TITLE
The notebook is no longer runnable

### ISSUE THREAD

**Issue by olexandr-konovalov** [losc-tutorial/LOSC_Event_tutorial#2]
Hello, I was trying to run the notebook on Binder but now it produces an error in "Matched filtering to find the signal" step:

    TypeError: slice indices must be integers or None or have an __index__ method

Is there a currently runnable version of your tutorials elsewhere? Please see also https://github.com/losc-tutorial/quickview/issues/3. Thanks.

**Comment by martinberoiz** [comment]
Hi,

Thanks for reporting this. The problem seems to be that NOVL is not an integer. The fix is to change the line:

```python
NOVL = NFFT/2
```
into 

```python
NOVL = NFFT // 2
```

it seems to be a remanent from the python 2 era.

I'll upload a working notebook soon.
